task done;
AndrewOliferchuk/pro2 pull request #8
Opened 2024-05-20 12:33 UTC by AndrewOliferchuk

2024-05-20 18:23 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-05-20 18:23 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/config/SecurityConfig.java
> +    public SecurityConfig(JwtAuthenticationFilter jwtAuthenticationFilter,
Let's use Lombok annotation `@RequiredArgsConstructor`

2024-05-20 18:23 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
```suggestion
    public UserLoginResponseDto login(@RequestBody @Valid UserLoginRequestDto requestDto) {
```

2024-05-20 18:23 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/AuthenticationController.java
>  @RequestMapping(value = "/auth")
```suggestion
@RequestMapping("/auth")
```

2024-05-20 18:23 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Let's use Spring constant HttpHeaders.AUTHORIZATION

2024-05-20 18:23 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Create constant for "Bearer "

2024-05-20 19:31 UTC, AndrewOliferchuk commented on src/main/java/com/example/demo/config/SecurityConfig.java
> +    public SecurityConfig(JwtAuthenticationFilter jwtAuthenticationFilter,
The code does not work with the annotation, but it works with the constructor

2024-05-21 05:53 UTC, Vasul-Pankiv approved these changes

2024-05-21 06:48 UTC, merged